env:
  contexts:
  - excludePaths: []
    name: baseline
    urls:
    - https://e-virtus.com/
  parameters:
    failOnError: true
    progressToStdout: false
jobs:
- install:
  - pscanrulesBeta
  type: addOns
  uninstall: []
- parameters:
    enableTags: false
    maxAlertsPerRule: 10
  type: passiveScan-config
- parameters:
    maxDuration: 1
    url: https://e-virtus.com/
  type: spider
- parameters:
    maxDuration: 0
  type: passiveScan-wait
- parameters:
    format: Long
    summaryFile: /home/zap/zap_out.json
  rules: []
  type: outputSummary
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: report-e-virtus.com--6422f034a39479692eeae4d2.json
    reportTitle: ZAP Scanning Report
    template: traditional-json
  type: report
